defaults:
  - model: generator
  - metrics: audio
  - datasets: librispeech_test
  - dataloader: librispeech
  - transforms: audio
  - _self_

sample_rate: ${datasets.test.sample_rate}

inferencer:
  device_tensors: ["data_object", "length"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: null
  seed: 1
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
