defaults:
  - model: generator
  - model/Discriminator@discriminator.waveform: waveform
  - model/Discriminator@discriminator.stft: stft
  - writer: cometml
  - metrics: audio
  - datasets: librispeech
  - dataloader: librispeech
  - transforms: audio
  - _self_

generator_optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4

discriminator_optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4

generator_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  factor: 1.0
  total_iters: 1000000000

discriminator_lr_scheduler:
  _target_: torch.optim.lr_scheduler.ConstantLR
  factor: 1.0
  total_iters: 1000000000

generator_loss_function:
  _target_: src.loss.SoundStreamGeneratorLoss
  lambda_adv: 1.0
  lambda_feat: 100.0
  lambda_rec: 1.0
  lambda_commit: 1.0
  scales: [2048, 1024, 512, 256, 128, 64]
  n_mels: 64

discriminator_loss_function:
  _target_: src.loss.SoundStreamDiscriminatorLoss

writer:
  run_name: soundstream
  loss_names:
    - loss
    - adv_loss
    - feat_loss
    - rec_loss
    - commitment_loss
    - discriminator_loss
    - real_loss
    - fake_loss

trainer:
  n_epochs: 150
  epoch_len: 300
  log_step: 10
  samples: 5
  device_tensors: ["data_object", "length"]
  resume_from: null
  device: auto
  override: True
  monitor: "off"
  save_period: 5
  early_stop: ${trainer.n_epochs}
  save_dir: "saved"
  seed: 1
